services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
networks:
  proxy:
    external: true
